# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

[ -f ~/.config/bash/bash_prompt ] && source ~/.config/bash/bash_prompt

[ -f ~/.config/aliases ] && source ~/.config/aliases

# command line uses vi
set -o vi
# make sure control l works in insert mode
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

