require "jer.navigation"
require "jer.lsp"
require "jer.completion"
require "jer.notify"
require "jer.debug"
require "jer.testing"
require "jer.version_control"
require "jer.terminal"
require "jer.help"
require "jer.formatting"
require "jer.silly"
require "jer.diagnostics"
require "jer.snippets"
require "jer.registers"
require "jer.appearance"
require "jer.python"
require "jer.tmux"
require "jer.miscellaneous"
require "jer.llms"
require "jer.rendering"
_, _ = pcall(require "jer.chat")
_, _ = pcall(require "jer.go")
require "jer.local".do_stuff()
