
require('jer.navigation')
require('jer.lsp')
require('jer.completion')
require('jer.notify')
require('jer.remaps')
require('jer.debug')
require('jer.testing')
require('jer.version_control')
require('jer.terminal')
require('jer.help')
require('jer.formatting')
require('jer.silly')
require('jer.chill')
require('jer.diagnostics')
require('jer.snippets')
require('jer.registers')

