"  Jeremy Mann's .vimrc

set number
set ai 
set relativenumber
set title
set noswapfile
syntax enable
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
set smartindent
set nohlsearch

set showmode
set showcmd

set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey

set incsearch
set ignorecase
set smartcase

set splitbelow splitright

nnoremap <SPACE> <Nop>
let mapleader="\<Space>"

" add line above/below without entering insert mode or moving cursor
nnoremap <silent> <leader>o :<C-u>call append(line("."),   repeat([""], v:count1))<CR>
nnoremap <silent> <leader>O :<C-u>call append(line(".")-1, repeat([""], v:count1))<CR>

" dturn on spell check
nnoremap <silent> <leader>sp :set spell!<CR>

call plug#begin('~/.vim/plugged')

call plug#end()

