---
- name: Install Stuff
  hosts: localhost
  become_user: true
  tasks:
    - name: Install Python
      package:
        name:
          - python-pip
          - python
        state: latest
      tags:
        - arch

    - name: Install core gnu stuff
      package:
        name:
          - sudo
          - htop
          - ripgrep
          - fzf
          - gcc
          - tree
          - wget
          - curl
          - htop
          - cmake
          - the_silver_searcher
          - pkg-config
          - fd
          - bat
        state: latest
      tags:
        - arch

    - name: Install zsh and bash
      package:
        name:
          - zsh
          - bash
        state: latest
      tags:
        - arch

    - name: Install Version Control Stuff
      package:
        name:
          - git
          - gitui
          - lazygit
          - git-delta
          - git-lfs
        state: latest
      tags:
        - arch

    - name: Install (Neo)Vim
      package:
        name:
          - neovim
          - vim
        state: latest
      tags:
        - arch

    - name: Install tmux
      package:
        name:
          - tmux
        state: latest
      tags:
        - arch

    - name: Install packer
      ansible.builtin.git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: "{{ lookup('env','HOME') + '/.local/share/nvim/site/pack/packer/start/packer.nvim' }}"
        update: no
        depth: 1

