---
- name: Install Stuff
  hosts: localhost
  become_user: true
  tasks:
    - name: Install Python
      package:
        name:
          - python-pip
          - python
        state: latest
      tags:
        - arch

    - name: Install core gnu stuff
      package:
        name:
          - htop
          - ripgrep
          - fzf
          - gcc
          - wget
          - curl
          - htop
          - cmake
          - the_silver_searcher
          - pkg-config
          - fd
          - bat
        state: latest
      tags:
        - arch

    - name: Install Version Control Stuff
      package:
        name:
          - git
          - gitui
          - lazygit
          - git-delta
          - git-lfs
        state: latest
      tags:
        - arch

    - name: Install (Neo)Vim
      package:
        name:
          - neovim
          - lazygit
        state: latest
      tags:
        - arch

    - name: Install tmux
      package:
        name:
          - tmux
        state: latest
      tags:
        - arch

    - name: Install Silly Stuff
      package:
        name:
          - asciiquarium
        state: latest
      tags:
        - arch

    - name: Install Node Stuff
      package:
        name:
          - nodejs
          - npm
        state: latest
      tags:
        - arch

    - name: Install zsh and bash
      package:
        name:
          - zsh
          - bash
        state: latest
      tags:
        - arch

    - name: Install Golang stuff
      package:
        name:
          - go
        state: latest
      tags:
        - arch

    - name: Install Rust stuff
      package:
        name:
          - rust
        state: latest
      tags:
        - arch

    - name: Install pandoc
      package:
        name:
          - pandoc
        state: latest
      tags:
        - arch

    - name: Install ffmpeg
      package:
        name:
          - ffmpeg
        state: latest
      tags:
        - arch

    - name: Install dictd
      package:
        name:
          - dictd
      tags:
        - arch

    - name: Install packer
      package:
        name:
          - packer
      tags:
        - arch

    - name: Install terraform
      package:
        name:
          - terraform
      tags:
        - arch

    - name: Install ruby
      package:
        name:
          - ruby
      tags:
        - arch

    - name: Install dictd
      package:
        name:
          - dictd
      tags:
        - arch

    - name: Install perl
      package:
        name:
          - perl
      tags:
        - arch

    - name: Install Lua
      package:
        name:
          - sqlitcwe
        state: latest
      tags:
        - arch

    - name: Install SQLite
      package:
        name:
          - sqlite
        state: latest
      tags:
        - arch

