---
- name: Install Language specific stuff
  hosts: localhost
  become_user: true
  vars_files:
    - packages.yml
  tasks:

    - name: Install Node Stuff
      become_user: true
      package:
        name:
          - nodejs
          - npm
        state: latest
      tags:
        - javascript

    - name: Install Golang stuff
      become_user: true
      package:
        name:
          - "{{ go[ansible_os_family] }}"
        state: latest
      tags:
        - go

    - name: Install Lua
      become_user: true
      package:
        name:
          - "{{ lua[ansible_os_family] }}"
        state: latest
      tags:
        - lua

    - name: Install Rust
      shell: curl https://sh.rustup.rs -sSf | bash -s -- -y
      tags:
        - rust

