---
- name: Install Python Dependencies for Standard Data Science Tasks
  hosts: localhost
  tasks:

    - name: Install jupyter python package
      pip:
        name: jupyter

    - name: Install matplotlib
      pip:
        name: matplotlib

    - name: Install altair
      pip:
        name: altair

    - name: Install seaborn
      pip:
        name: seaborn

    - name: Install scikit-learn
      pip:
        name: scikit-learn

    - name: Install jupyter
      pip:
        name: jupyter

    - name: Install scipy
      pip:
        name: scipy

    - name: Install pandas
      pip:
        name: pandas

    - name: Install numpy
      pip:
        name: numpy

    - name: Install Streamlit
      pip:
        name: streamlit

    - name: Install SQLAlchemy
      pip:
        name: sqlalchemy

    - name: Install PyTorch
      pip:
        name: torch

    - name: Install Langchain
      pip:
        name: langchain

    - name: Install OpenAI
      pip:
        name: openai

    - name: Install LangChain
      pip:
        name: langchain

