export CLICOLOR=1
export EDITOR=nvim
export IPYTHONDIR=$XDG_CONFIG_HOME/ipython
export TASKRC=$XDG_CONFIG_HOME/task/taskrc
export LESSHISTFILE="-"
export PTPYTHON_CONFIG_HOME="$XDG_CONFIG_HOME/ptpython"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export ANSIBLE_CONFIG=$XDG_CONFIG_HOME/ansible/ansible.cfg
export TMUX_CONFIG=$XDG_CONFIG_HOME/tmux/.tmux.conf
export CODEDIR=$BASEDIR/code
export MEASUREMENT_DATA_FILEPATH=$BASEDIR/personal_data/numeric_measurement_data.csv
export DOTFILES=$BASEDIR/dotfiles
export WRITING=$BASEDIR/writing
export LG_CONFIG_FILE=$XDG_CONFIG_HOME/lazygit/config.yml
export SCRATCH_FILE=$BASEDIR/scratch
export AUDIO_DATA_DIR=$BASEDIR/audio
