export CLICOLOR=1
export EDITOR=nvim
export IPYTHONDIR=$XDG_HOME_CONFIG/ipython
export TASKRC=$XDG_HOME_CONFIG/task/taskrc
export LESSHISTFILE="-"
export PTPYTHON_CONFIG_HOME="$XDG_HOME_CONFIG/ptpython"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export ZDOTDIR=$XDG_HOME_CONFIG/zsh
export ANSIBLE_CONFIG=$XDG_HOME_CONFIG/ansible/ansible.cfg
export TMUX_CONFIG=$XDG_HOME_CONFIG/tmux/.tmux.conf
export CODEDIR=$BASEDIR/code
export MEASUREMENT_DATA_FILEPATH=$BASEDIR/personal_data/numeric_measurement_data.csv
export DOTFILES=$BASEDIR/dotfiles
export WRITING=$BASEDIR/writing
export LG_CONFIG_FILE=$XDG_HOME_CONFIG/lazygit/config.yml
export SCRATCH_FILE=$BASEDIR/scratch
